POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "example@email.com",
  "name": "john doe",
  "password": "password123!"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "example@email.com",
  "password": "password123!"
}

### 
POST http://localhost:3000/token/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc2NzE1ODYyNywiZXhwIjoxNzY4MzY4MjI3fQ.yR5qsEBNWyBNrVmD74dISaDnrRasArijlPuG89HReq8; Path=/; HttpOnly; Secure; SameSite=None

# HTTP/1.1 200 OK
# X-Powered-By: Express
# Set-Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc2NzE1ODYyNywiZXhwIjoxNzY4MzY4MjI3fQ.yR5qsEBNWyBNrVmD74dISaDnrRasArijlPuG89HReq8; Path=/; HttpOnly; Secure; SameSite=None
# Content-Type: application/json; charset=utf-8
# Content-Length: 161
# ETag: W/"a1-GFWaZPR56JI8FpqjOGl8v0tGXjU"
# Date: Wed, 31 Dec 2025 05:23:47 GMT
# Connection: close

# {
#   "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc2NzE1ODYyNywiZXhwIjoxNzY3MTYyMjI3fQ.7bBKZ_oJbqm0OsYEbqCybogri-t8tzeApPCBKJntsKE"
# }

###
POST http://localhost:3000/session-login
Content-Type: application/json

{
  "email": "example@email.com",
  "password": "password123!"
}
