POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "example2@email.com",
  "name": "john doe",
  "password": "password123!"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "example2@email.com",
  "password": "password123!"
}
